package com.pojo;

// Generated Dec 9, 2020 1:39:52 PM by Hibernate Tools 3.4.0.CR1

/**
 * Emp generated by hbm2java
 */
public class Emp implements java.io.Serializable {

	private Integer id;
	private String name;
	private String email;
	private String phone;

	public Emp() {
	}

	public Emp(String name, String email, String phone) {
		this.name = name;
		this.email = email;
		this.phone = phone;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

}
